### ISSUE TITLE
pagination error in igv

### ISSUE THREAD

**Issue by JasonLing95** [eastgenomics/Genetics_Ark#61]
<img width="1033" alt="Screenshot 2024-04-17 at 12 10 32" src="https://github.com/eastgenomics/Genetics_Ark/assets/60819172/d8ace921-d6c4-48d8-ba30-990b76ec7ce4">

**Comment by corbin-chris** [comment]
Closed by https://github.com/eastgenomics/Genetics_Ark/pull/65
